name: Build Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme

      - name: Build HTML
        run: |
          cd source
          make html

      - name: Deploy to GitHub Pages
<<<<<<< HEAD
        uses: peaceiris/actions-gh-pages@v4
=======
        uses: peaceiris/actions-gh-pages@v3
>>>>>>> caaf93e (Fix publish_dir to correct build/html path)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
